<?php
ob_start ();
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lib_picsaca{
	private $CI;

	public function __construct(){
		$this->CI =& get_instance();
	}
	
	public function delete($checkbox)
	{
		$user = "giundatmail@gmail.com";
		$pass = "trung8995";
		$albumId = "5987655189048433073";
		$sitename = 'FREE';
		$images_in_slide = 20;
		$max_images_size = 100; //100 = 100MB
		require APPPATH . '/third_party/Zend/Loader.php';
		Zend_Loader::loadClass('Zend_Gdata');
		Zend_Loader::loadClass('Zend_Gdata_ClientLogin');
		Zend_Loader::loadClass('Zend_Gdata_Photos');
		Zend_Loader::loadClass('Zend_Http_Client');

		$serviceName = Zend_Gdata_Photos::AUTH_SERVICE_NAME;
		$client = Zend_Gdata_ClientLogin::getHttpClient($user, $pass, $serviceName);

// update the second argument to be CompanyName-ProductName-Version
	$gp = new Zend_Gdata_Photos($client, "Google-DevelopersGuide-1.0");
	$query = $gp->newUserQuery();

	// indicate the user's feed to retrieve
	$query->setUser("default");
	// set to only return photos
	// the default kind value for a user feed is to include only albums
	$query->setKind("photo");

	//$query->setMaxResults(10);
/////////////////////////////////////////////

/////////////////////////////////////////////
    // we're passing null for the username, as we want to send
    // additional query parameters generated by the UserQuery class
    $userFeed = $gp->getUserFeed(null, $query);

    // because we specified 'photo' for the kind, only PhotoEntry objects
    // will be contained in the UserFeed
$i=1;
    foreach ($userFeed as $photoEntry) {
		
		if ($photoEntry->getMediaGroup()->getThumbnail() != null) {
		  $mediaThumbnailArray = $photoEntry->getMediaGroup()->getThumbnail();
		  $firstThumbnailUrl = $mediaThumbnailArray[1]->getUrl();
		}
		$link = $photoEntry->getLink('alternate')->getHref();
		$title = $photoEntry->getTitle()->getText();
		$anh=explode('/s144/', $firstThumbnailUrl);
		$linkgoc=$anh[0].'/'.$anh[1];
		$linkanh=$anh[0].'/s1366/'.$anh[1];
		$linkthumb=$anh[0].'/s100-c/'.$anh[1];
		foreach($checkbox as $key => $val){
		if($i==$val)$gp->deletePhotoEntry($photoEntry, true);
		}
$i++;    }
		
	}
}